import {QUERY_ASK_CONST,QUERY_ASK_DETAIL_CONST} from "./ask";
import {QUERY_JOB_CONST} from "./job";
import {QUERY_MEETUP_CONST} from "./meetup";
import {QUERY_NEWS_LETTER_CONST, QUERY_NEWS_LETTER_DETAIL_CONST} from "./newsletter";

export const QUERY_ASK = QUERY_ASK_CONST;
export const QUERY_JOB = QUERY_JOB_CONST;
export const QUERY_MEETUP = QUERY_MEETUP_CONST;
export const QUERY_ASK_DETAIL = QUERY_ASK_DETAIL_CONST;
export const QUERY_NEWS_LETTER  = QUERY_NEWS_LETTER_CONST;
export const QUERY_NEWS_LETTER_DETAIL  = QUERY_NEWS_LETTER_DETAIL_CONST;

